- name: apt cache is up to date
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: apt packages are up to date
  apt:
    upgrade: yes

- name: apt https repository requirements are satisfied
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common
